name: Code_quality

on: [push]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.13
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install deps and activate virt
      if: steps.cache-deps.cache-hit != 'true'
      run:
        poetry install --no-interaction
    - name: Activate virt
      run:
        source .venv/bin/activate
    - name: Run black
      run: |
        poetry run black vksearch/manage.py
        poetry run black vksearch/siteauth/apps.py
        poetry run black vksearch/siteauth/forms.py
        poetry run black vksearch/siteauth/models.py
        poetry run black vksearch/siteauth/tests/test_siteuser_login.py
        poetry run black vksearch/siteauth/tests/test_siteuser_register.py
        poetry run black vksearch/siteauth/migrations/0001_initial.py
        poetry run black vksearch/siteauth/urls.py
        poetry run black vksearch/siteauth/views.py
        poetry run black vksearch/vkgroup/apps.py
        poetry run black vksearch/vkgroup/migrations/0001_initial.py
        poetry run black vksearch/vkgroup/forms.py
        poetry run black vksearch/vkgroup/migrations/0002_alter_community_description_alter_community_members_and_more.py
        poetry run black vksearch/vkgroup/migrations/0003_alter_community_type_alter_communitytype_name.py
        poetry run black vksearch/vkgroup/migrations/0004_alter_communitytype_name.py
        poetry run black vksearch/vkgroup/migrations/0005_alter_community_description.py
        poetry run black vksearch/vkgroup/migrations/0007_alter_audienceprofile_sex_alter_community_age_vk.py
        poetry run black vksearch/vkgroup/migrations/0008_alter_community_name_alter_community_site.py
        poetry run black vksearch/vkgroup/migrations/0009_alter_community_site.py
        poetry run black vksearch/vkgroup/migrations/0010_alter_community_members_alter_community_name.py
        poetry run black vksearch/vkgroup/migrations/0011_alter_community_members.py
        poetry run black vksearch/vkgroup/migrations/0012_alter_community_age_vk.py
        poetry run black vksearch/vkgroup/migrations/0006_agerange_country_audience_community_community_age_vk_and_more.py
        poetry run black vksearch/vkgroup/migrations/0013_alter_community_status.py
        poetry run black vksearch/vkgroup/migrations/0014_alter_community_deactivated_and_more.py
        poetry run black vksearch/vkgroup/migrations/0015_alter_community_name_alter_community_site_and_more.py
        poetry run black vksearch/vkgroup/migrations/0017_alter_community_description.py
        poetry run black vksearch/vkgroup/migrations/0016_alter_community_description_alter_community_name_and_more
        poetry run . --check
    - name: Run isort
      run:
        poetry run isort . --check-only --profile black
    - name: Run flake8
      run:
        poetry run flake8 .
    - name: Run Mypy
      run:
        poetry run mypy pandaseda
